# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_by',
            new_name='user',
        ),
    ]
